### ISSUE TITLE
Features List?

### ISSUE THREAD

**Issue by bdyetton** [pocketbroadcast/link-to-midi#1]
Hi,
I'm looking for a Link to Midi converter such as this one. I'd like to use Serato DJ (Link enabled software) to control lighting. 
This project of yours looking promising. Is it complete, and what are the features?
Thanks.

**Comment by pocketbroadcast** [comment]
This bridge can handle incoming bpm changes from other link enabled devices (in your case Serato DJ) and set the tempo on connected midi devices.

I hope this answer was helpful.
If you need additional features feel free to contribute, or post a feature request.

**Comment by bdyetton** [comment]
Great thanks. I'll give it a go.
